### ISSUE TITLE
max container validation fails to run

### ISSUE THREAD

**Issue by unsub** [helgatheviking/woocommerce-mix-and-match-min-max#3] opened 2016-01-27 05:50 UTC
Hi there,

Great plugin - exactly what I need. However, there appears to be some kind of issue with recognizing the 'max'.
Debug is no help, alas.
Initially, 404 on the minified js. Turning on debug didn't help, so I just changed the filename temporarily.

Console is giving me your debug message - "bacon" (which makes me smile without fail.)
But messages don't appear anymore. 

The one thing of interest that I've noticed is that the individual products in the mix-&-match selection now have a maximum selectable number: ie I set a minimum of 4, a maximum of 7. It doesn't function, but now the individual items can only go up to seven.... 

Adding to cart with more than 'minimum' amount fails with request to only add the minimum. So it's not just the js. Wish I could give you more of a report... still digging. 

I'm not the programmer that you are, by any stretch, but if I discover anything I will let you know.
And if you have any suggestions on where to look, I'd be very appreciative.
- Gabriel

**Comment by helgatheviking** [comment] 2016-01-27 15:58
Hi Gabriel,

I'm glad to hear that this is getting some use. I just updated a 1.0.1 release that resolves the minified script issue (ie: the lack of one) and I think I have isolated the add to cart problem, but I couldn't say exactly when I will be able to get it resolved. 

cheers,
-kathy

@franticpsyx as far as I can tell, the issue is in MNM's add to cart validation, specifically [here](https://github.com/woothemes/woocommerce-mix-and-match-products/blob/master/includes/class-wc-mnm-cart.php#L273-L285) as MNM returns `false` before min/max ever has chance to validate the container.

**Comment by unsub** [comment] 2016-01-28 05:26
Hi Kathy,

Thanx for the update. It's a great addition to MNM. 
- Gabriel

**Comment by helgatheviking** [comment] 2016-02-05 14:07
@franticpsyx what do you think of https://github.com/woothemes/woocommerce-mix-and-match-products/commit/555622e22650881a229fd3013037791b21fc6da3? Will that solve this?  Did I just muck it up more?

**Comment by manospsyx** [comment] 2016-02-05 14:13
@helgatheviking had some similar issues with CP - the cause was that `get_total_quantity` in WC 2.5 may return `null` when not managing stock. Could it be related to this issue, as well?

**Comment by helgatheviking** [comment] 2016-02-05 14:30
Thanks for jumping in Manos. I will have to check that, but I still think that [this](https://github.com/woothemes/woocommerce-mix-and-match-products/blob/master/includes/class-wc-mnm-cart.php#L273-L276) means we're returning `false` and showing the regular MNM error before the container can be validated from an extension. 

@unsub Could you let us know if you are or are not managing stock for your products?

**Comment by unsub** [comment] 2016-02-05 18:50
@helgatheviking: nope, not managing stock on these products. I'm away from the office at the moment, but I'll test when I get back this evening.

**Comment by unsub** [comment] 2016-02-06 04:20
Hi @helgatheviking I have tested w/ stock mgmt. turned on, and stock set to 1000. Still the same result.
I have some time this wknd to dig around, if I make any headway I will post. 

PS: I'm sorry the title of this issue thread is so silly and vague... I didn't really think that one through :( 
Each time I see it I kind of wince LOL

**Comment by helgatheviking** [comment] 2016-02-06 04:45
@unsub I don't know if that's wholly better as a title, but I tried. 

I'm about 90% certain that the issue is with validation in the MNM plugin... specifically `includes/class-wc-mnm-cart.php` lines 263-285. 

This mini extension latches on to the `woocommerce_mnm_add_to_cart_validation` filter, however MNM tests its fixed container/unlimited size rules and returning false on failure _before_ that filter is ever run. The result is that the min/max plugin isn't validating at all. so what is needed, is a way to check all of the things in MNM, and still override the result from the min/max extension. 

You can't see what's happening on the private woo repos, but my first attempt was to replace those lines in `class-wc-mnm-cart.php` with:

```
        // the number of items allowed to be in the container
        $limit = intval( get_post_meta( $product_id, '_mnm_container_size', true ) );
        $error_message = '';
        $valid_container = false;
        // validate that the quantity matches and check stock for stock-managed bundled items
        if ( $mnm_stock->validate_stock() && $limit === $mnm_stock->get_total_quantity() ) {
            $valid_container = true;
        } 
        // allowing extension to also validate the container
        if ( ! has_filter( 'woocommerce_mnm_add_to_cart_validation' ) && ! apply_filters( 'woocommerce_mnm_add_to_cart_validation', $valid_container, $mnm_stock, $product ) ) {

            $passed_validation = false;
            // validate that an unlimited container has some items
            if ( $limit === 0 && $mnm_stock->get_total_quantity() === 0 ) {
                wc_add_notice ( sprintf( __( 'You have not selected any items. Please choose at least 1 item for &quot;%s&quot;.', 'woocommerce-mix-and-match-products' ), $product->get_title() ) );
            // validate the number of items in the container matches exactly
            } elseif ( $limit > 0 && $mnm_stock->get_total_quantity() > $limit ) {
                wc_add_notice ( sprintf( __( 'You have selected too many items. Please choose %d items for &quot;%s&quot;.', 'woocommerce-mix-and-match-products' ), $limit, $product->get_title() ) );
            } elseif ( $limit > 0 && $mnm_stock->get_total_quantity() < $limit ) {
                wc_add_notice ( sprintf( __( 'You have selected too few items. Please choose %d items for &quot;%s&quot;.', 'woocommerce-mix-and-match-products' ), $limit, $product->get_title() ) );
            } 
        }
    }
    return $passed_validation;
```

Something about that seems iffy to me, but probably because I didn't get to test it. So if you wanted to test that it'd be great.

**Comment by unsub** [comment] 2016-02-06 16:53
@helgatheviking I gave it try, but I'm afraid nothing changed.
I get the flash of the message box (in blue) and then it slides up.
Still seems to be counting the wrong thing, ie: the individual products in the mnm bundle, rather than the total of all the products. If I set my MAX

**Comment by unsub** [comment] 2016-02-06 17:01
@helgatheviking 
With that code addition, the min/max rules do not seem to apply. 
BTW it's line 259 in my version, don't know if I'm out of date? will check. But the min/max validation ceases, nonetheless.

**Comment by unsub** [comment] 2016-02-06 21:45
Still looking, haven't had any luck yet. I am very sure that you are correct. add_to_cart_validation is not called at all except when 'min' is matched by the product selection. Will try a bit more today. Thanks for the update :)

**Comment by unsub** [comment] 2016-02-07 23:00
@helgatheviking well... I've done some really hackish thing, I've created a static range of minimum through minimum + 5, and just wedged it into the add_to_cart_validation function in that page you referenced above. I can now add to cart within that range... so, although it's not something I would put in production (or publish! LOL) we know for certain that you are right about where it's crashing. Just need to maybe override the whole function. Having a tough time figuring out what that validation is hooked on to, so I can do that...

line 259 > 282

`// the number of items allowed to be in the container
            $limit = intval( get_post_meta( $product_id, '_mnm_container_size', true ) );
            $max_limit = $limit + 4;
            $error_message = false;

```
        // validate that an unlimited container has some items
        if ( $limit === 0 && $mnm_stock->get_total_quantity() === 0 ) {
            $error_message = sprintf( __( 'You have not selected any items. Please choose at least 1 item for &quot;%s&quot;.', 'woocommerce-mix-and-match-products' ), $product->get_title() );
        // validate the number of items in the container matches exactly
        } elseif ( $limit > 0 && $mnm_stock->get_total_quantity() > $max_limit ) {
            $error_message = sprintf( __( 'You have selected too many items. Please choose %d items for &quot;%s&quot;.', 'woocommerce-mix-and-match-products' ), $limit, $product->get_title() );
        } elseif ( $limit > 0 && $mnm_stock->get_total_quantity() < $limit ) {
            $error_message = sprintf( __( 'You have selected too few items. Please choose %d items for &quot;%s&quot;.', 'woocommerce-mix-and-match-products' ), $limit, $product->get_title() );
        }

        if( $error_message ){
            wc_add_notice( $error_message, 'error' );
            return false;
        }

        // Check stock for stock-managed bundled items, allowing extensions to also validate the container
        // If out of stock, don't proceed
        if ( ! apply_filters( 'woocommerce_mnm_add_to_cart_validation', $mnm_stock->validate_stock(), $mnm_stock, $product ) ) {
            return false;
        }`
```

**Comment by helgatheviking** [comment] 2016-02-08 13:19
@unsub i'm trying really hard to get my Ninja Forms extension updated right now, but as soon as I finish that I will try to take another look at this. In the mean time, I had another idea that you could maybe test.

replaces lines 258-285 in `class-wc-mnm-cart.php`:

```
if ( ! has_filter( 'woocommerce_mnm_add_to_cart_validation' ) ) {

    // the number of items allowed to be in the container
    $limit = intval( get_post_meta( $product_id, '_mnm_container_size', true ) );
    $error_message = false;
    // validate that an unlimited container has some items
    if ( $limit === 0 && $mnm_stock->get_total_quantity() === 0 ) {
        $error_message = sprintf( __( 'You have not selected any items. Please choose at least 1 item for &quot;%s&quot;.', 'woocommerce-mix-and-match-products' ), $product->get_title() );
    // validate the number of items in the container matches exactly
    } elseif ( $limit > 0 && $mnm_stock->get_total_quantity() > $limit ) {
        $error_message = sprintf( __( 'You have selected too many items. Please choose %d items for &quot;%s&quot;.', 'woocommerce-mix-and-match-products' ), $limit, $product->get_title() );
    } elseif ( $limit > 0 && $mnm_stock->get_total_quantity() < $limit ) {
        $error_message = sprintf( __( 'You have selected too few items. Please choose %d items for &quot;%s&quot;.', 'woocommerce-mix-and-match-products' ), $limit, $product->get_title() );
    }
    if( $error_message ){
        wc_add_notice( $error_message, 'error' );
        return false;
    }

}

// Check stock for stock-managed bundled items, allowing extensions to also validate the container
// If out of stock, don't proceed
if ( ! apply_filters( 'woocommerce_mnm_add_to_cart_validation', $mnm_stock->validate_stock(), $mnm_stock, $product ) ) {
    return false;
}
return $passed_validation;
```

**Comment by unsub** [comment] 2016-02-08 20:10
@helgatheviking holy mackerel! that works :) Needed one more curly-brace, but the cart validation is working great now. I'll have a go @ the JS and see if I can find a patch (message box and add-to-cart button actions), but first I shall pore over what you did here and see if I can learn something about how the real professionals do it! :+1: 
Thanks so much for working on this.

**Comment by helgatheviking** [comment] 2016-02-08 22:06
@unsub My ninja forms extension is really kicking my butt, but I'm glad to hear that I may have stumbled on to something. Can you explain the problem you are seeing with the JS? I think I was under the impression that the problem was only validation. 

@franticpsyx does skipping the quantity validation if `has_filter('woocommerce_mnm_add_to_cart_validation')` make sense to you? is there a hidden downside I am not seeing?

**Comment by unsub** [comment] 2016-02-09 00:32
@helgatheviking The nifty little blue message box at the bottom appears for about 0.25 seconds then slides up and disappears on page load. The "add to cart" button is visible and clickable. I was assuming the behaviour was intended to be something like the default MNM state, ie: message box gives similar and complimentary information to the add-to-cart state message box at the top? and the add-to-cart button is only visible/clickable when an appropriate number of products is reached / not exceeded. I thought that it might be related to the same thing.
I'm actually not terrible w/ JS, so I'm happy to pick away at that. Kind of fun, actually. (assuming I am correct about what it is supposed to do? ) 
I wish you luck and gods' speed w/ Ninja Forms :)

**Comment by helgatheviking** [comment] 2016-02-09 01:58
I can't quite recreate that. Are you using the updated 1.0.1 and are you therefore sure you are loading the scripts? I forgot to include the minified scripts in 1.0.0.

for however long this stays active, the error message and button seems to behave like you'd expect
https://wordpress-helgatheviking.c9.io/product/mix-and-match-t-shirt-up-to-10/

**Comment by manospsyx** [comment] 2016-02-09 06:05
> does skipping the quantity validation if `has_filter('woocommerce_mnm_add_to_cart_validation')` make sense to you? is there a hidden downside I am not seeing?

Hmmm doesn't sound too elegant... I think I would either:
- use separate hooks to validate the min/max qties, or
- only return/add a notice after the validation filter has run without issues.

**Comment by helgatheviking** [comment] 2016-02-09 13:10
It actually seemed slightly _more_ elegant than my first thought, because it has zero effect on those not customizing MNM. But that's probably because the [first attempt](https://github.com/helgatheviking/woocommerce-mix-and-match-min-max/issues/3#issuecomment-180680329) was really ugly. 

I think the trouble with "only return/add a notice after the validation filter has run without issues." is that we've traditionally never sent a `$passed=true`. We typically only trigger a `false` if the validation fails somewhere. So if it doesn't fail the min/max quantity it still gets validated against the MNM strict quantity limit. 

Needs coffee....doesn't like coffee... conundrum.

**Comment by unsub** [comment] 2016-02-10 05:38
@helgatheviking 
huh... well yours does work, but unfortunately I can't get mine to.
Just went through a new install - Fresh and empty WP 4.4.2, default (2016) theme, vanilla woocommerce with sample products imported, with no addons except for mix and match, and mix and match min max (cloned from repo - 1.01). As soon as I install min / max, the js message / add-to-cart button behaviour stops working. Made the critical change to the mnm-cart file again, still nothing. Deactivated, re-activated, created fresh new mix-and-match product, and.... damn. Nothing. 
No message in console, no missing files. Stumped.  :?

But the validation is working brilliantly anyway :) 
As for the JS, I will see if at some point I can make it "not work" a little less quietly. Currently it's downright laconic. I have no idea what it's thinking. I'm sorry that I can't report anything useful.

**Comment by unsub** [comment] 2016-02-14 05:37
hi @helgatheviking 
I've put up a [test site](http://www.studio440.ca/minmax/product/gabriels-birthday-bundle/) and will send you admin creds if  you should so desire.
Haven't had much time this wknd, but have at least discovered that <code>total_qty</code> returns undefined in add-to-cart-mnm-minmax.js (as does 'c' in the minified version) . Will dig some more tomorrow if I'm home for long enough, LOL. 

Hope your Ninja Forms project is going well. :)

**Comment by unsub** [comment] 2016-02-14 07:09
@helgatheviking 
Oh jeepers - i had a sudden brainstorm (Yes, I have a brain....) and so because I was not able to find any other snags in add-to-cart-mnm-minmax.js,  I went back to your functioning test site and copied the contents of add-to-cart-mnm.js from the mix-and-match plugin (it's not the minified one that's loading there) and pasted into the same file on my local test server, and it works.... what? 
So, bcause I'm lazy, I didn't bother switching to non-minified, I just pasted it into the .min.js version. So I'm not sure... further mucking about is necessary.

**Comment by helgatheviking** [comment] 2016-02-14 14:01
@franticpsyx what if we move

```
            $error_message = false;
            // validate that an unlimited container has some items
            if ( $limit === 0 && $mnm_stock->get_total_quantity() === 0 ) {
                $error_message = sprintf( __( 'You have not selected any items. Please choose at least 1 item for &quot;%s&quot;.', 'woocommerce-mix-and-match-products' ), $product->get_title() );
            // validate the number of items in the container matches exactly
            } elseif ( $limit > 0 && $mnm_stock->get_total_quantity() > $limit ) {
                $error_message = sprintf( __( 'You have selected too many items. Please choose %d items for &quot;%s&quot;.', 'woocommerce-mix-and-match-products' ), $limit, $product->get_title() );
            } elseif ( $limit > 0 && $mnm_stock->get_total_quantity() < $limit ) {
                $error_message = sprintf( __( 'You have selected too few items. Please choose %d items for &quot;%s&quot;.', 'woocommerce-mix-and-match-products' ), $limit, $product->get_title() );
            }
            if( $error_message ){
                wc_add_notice( $error_message, 'error' );
                return false;
            }
```

to it's own method and attach it to the `woocommerce_mnm_add_to_cart_validation` filter? That way it could be unhooked from another extension. Is that less hackish?

**Comment by helgatheviking** [comment] 2016-02-14 14:11
@unsub I actually finished the Ninja Forms project (still need to redo the documentation) so I can try to give this a shot. I think the thing will be just finding the most elegant solution because there are a couple of ways I could do this. 

> (it's not the minified one that's loading there) and pasted into the same file on my local test server, and it works.... what?

If that's the case, I wonder if I didn't minify the latest release. That'd be a boneheaded move, but it doesn't mean I didn't do it. It's always a good idea to work with the unminified version when testing. You can just define `SCRIPT_DEBUG` in your `wp-config.php` and that will automatically load the regular scripts.

**Comment by manospsyx** [comment] 2016-02-16 07:23
@helgatheviking how about just validating for both min + max, and then filtering those min/max values from the mini-extension? I believe we are doing something similar within the product class.

**Comment by helgatheviking** [comment] 2016-02-16 18:13
@franticpsyx can you elaborate a little? I'm not sure i follow what you mean. sorry to keep harassing you with this, but i am having a bit of a brain fart.

**Comment by helgatheviking** [comment] 2016-02-16 18:31
I thought I had it, but nope. :) Just adding filters for min/max isn't quite enough because the messages also change. So what about filtering the `$error_message`?

**Comment by manospsyx** [comment] 2016-02-17 13:49
@helgatheviking 

Method 1) Handle the error message inside MnM and only filter the quantities from the mini-extension. If min=max, we return the standard error message.

Method 2) We `return false` and display the message if a `$qty_validation` message exists, and simply filter the error message from the mini-extension, as you say ;)

**Comment by helgatheviking** [comment] 2016-02-17 20:23
@unsub gabriel, please try patching `class-wc-mnm-cart.php` with [this](https://gist.github.com/helgatheviking/3864b07f0a65c1bd229e). And using the latest version of min/max which I will push up in a minute. maybe just without JS as I see a slight issue there that hopefully i will get fixed before you get testing.

**Comment by helgatheviking** [comment] 2016-02-17 22:02
I think this will be closed by MNM commit [13dd4ca](https://github.com/woothemes/woocommerce-mix-and-match-products/commit/13dd4caf54f0faccd10d1711dfae1aaeec3fdb94) in conjunction with this plugin's eb2ad8530e1d735f210697fc58e3a6c422955336

**Comment by unsub** [comment] 2016-02-18 05:03
@helgatheviking That appears to work. Nicely done :) JS is working well, too. 
Really fantastic work with these plugins, thank you so much!

**Comment by helgatheviking** [comment] 2016-02-24 14:07
Great, glad it is working!

**Closed as completed by helgatheviking** 2016-02-24 14:07 UTC
